#!/bin/sh
. /usr/share/libubox/jshn.sh

_log() {
	logger -t "force-unmount" "$1"
}

# compare_pid process_id pid
# 当process_id与pid相等，或process_id是pid子进程时返回0，否则返回1
compare_pid() {
	local process_id=$1
	local pid=$2
	local p
	[ -n "$pid" ] && [ -n "$process_id" ] || return 1
	[ "$process_id" -eq "$pid" ] && return 0
	for p in $(busybox pgrep -P "$pid"); do
		compare_pid "$process_id" "$p" && return 0
	done
	return 1
}

# stop_occupying_service mount_point
# 停止所有占用挂载点的服务
# example: stop_occupying_service /mnt/sda1
stop_occupying_service() {
	local mountpoint process_id services service instances instance kill_flag pid running

	json_init
	json_load "$(ubus call service list)"
	json_get_keys services

	mountpoint="$1"
	for process_id in $(lsof -t "$mountpoint"); do
		for service in $services; do
			kill_flag=0
			if json_is_a $service object; then
				json_select $service
				if json_is_a instances object; then
					json_select instances
					json_get_keys instances
					for instance in $instances; do
						if json_is_a $instance object; then
							json_select $instance
							json_get_var pid pid
							json_get_var running running
							[ -n "$running" ] && [ "$running" -eq 1 ] &&
								compare_pid "$process_id" "$pid" && kill_flag=1
							json_select ..
						fi
					done
					json_select ..
				fi
				json_select ..
			fi
			[ $kill_flag -eq 1 ] && {
				_log "stopping service: ${service}"
				/etc/init.d/$service stop
			}
		done
	done
}

# kill_occupying_process mount_point force_kill
# 结束所有占用挂载点的进程
# example: kill_occupying_process /mnt/sda1 1
kill_occupying_process() {
	local mountpoint process_id force_kill
	mountpoint="$1"
	force_kill="$2"
	for process_id in $(lsof -t "$mountpoint"); do
		_log "killing process: $(cat /proc/$process_id/comm)"
		if [ "$force_kill" -eq 1 ]; then
			kill -9 "$process_id"
		else
			kill "$process_id"
		fi
	done
}

MAX_TRY=5

[ "$#" -eq 1 ] || exit 1

# 去除挂载点路径中连续多余的'/'，例如 /mnt//sda1 -> /mnt/sda1
# 去除挂载点路径末尾的'/'，例如 /mnt/sda1/ -> /mnt/sda1
mountpoint="$(echo "$1" | sed -e 's#/\+#/#g' -e 's#/*[[:space:]]*$##g')"

[ -e "$mountpoint" ] || {
	_log "can't unmount ${mountpoint}: No such file or directory"
	exit 1
}

if awk '{print $2}' /proc/mounts | grep -q "^${mountpoint}$"; then
	for try_count in $(seq $MAX_TRY); do
		_log "unmounting ${mountpoint}: try count: ${try_count}"
		stop_occupying_service "$mountpoint"
		if [ "$try_count" -gt 1 ] || [ "$try_count" -eq "$MAX_TRY" ]; then
			kill_occupying_process "$mountpoint" 1
		else
			kill_occupying_process "$mountpoint" 0
		fi
		sync
		umount "$mountpoint"
		exit_code="$?"
		[ "$exit_code" -eq 0 ] && {
			_log "${mountpoint} successfully unmounted"
			exit 0
		}
	done
	_log "can't unmount ${mountpoint}"
	exit "$exit_code"
else
	_log "${mountpoint} is not mounted"
	exit 1
fi
