#!/bin/sh
[ "$(uci get syncdial.config.enabled)" = "1" ] && \
	[ "$(uci get syncdial.config.old_frame)" = "1" ] && \
	[ "$DEVICE" = "$(uci get network.wan.ifname)" ] && \
	[ "$ACTION" = "ifup" ] && {
	ifname=$(uci get network.wan.ifname)
	wannum=$(uci get syncdial.config.wannum)
	for i in $(seq 1 $wannum)
	do
		[ -d /sys/class/net/sdveth$i ] || {
			ip link add link $ifname name sdveth$i type macvlan
			ifconfig sdveth$i hw ether $(echo $(cat /sys/class/net/$ifname/address|awk -F ":" '{print $1":"$2":"$3":"$4":"$5":" }')$(echo "" | awk -F ":" '{printf("%X\n", 16+i);}' i=$i))
			ifconfig sdveth$i up
		}
	done
}
