#
# Copyright (C) 2010-2011 OpenWrt.org
#
# This is free software, licensed under the GNU General Public License v2.
# See /LICENSE for more information.
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI Support for cpulimit
LUCI_DEPENDS:=+cpulimit
LUCI_PKGARCH:=all
PKG_VERSION:=0.11
PKG_RELEASE:=14

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
